EasyShop.Web/Controllers/AccountController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace EasyShop.Web.Controllers
{
    [Authorize]
    public class AccountController : BaseController
    {
        // GET: Account
        public ActionResult Index()
        {
            return View();
        }
    }
}

EasyShop.Web/Controllers/AuthController.cs
using EasyShop.Models.Domain;
using EasyShop.Models.View;
using EasyShop.Services.Interfaces;
using Microsoft.AspNet.Identity;
using Microsoft.Owin.Security;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace EasyShop.Web.Controllers
{
    public class AuthController : Controller
    {
        private readonly UserManager<User> _userManager;

        public AuthController() : this(BaseController.UserManagerFactory.Invoke())
        {
            
        }

        public AuthController(UserManager<User> userManager)
        {
            this._userManager = userManager;
        }

        [AllowAnonymous]
        [HttpGet]
        // GET: Login
        public ActionResult Login(string returnUrl = "")
        {
            var model = new UserLoginViewModel()
            {
                ReturnUrl = returnUrl
            };
            return View(model);
        }

        [HttpPost]
        [AllowAnonymous]
        public async Task<ActionResult> Login(UserLoginViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }

            var user = await _userManager.FindAsync(model.Email, model.Password);

            if(user != null)
            {
                var identity = await _userManager.CreateIdentityAsync(user, DefaultAuthenticationTypes.ApplicationCookie);

                var authenticationManager = GetAuthManager();

                authenticationManager.SignIn(identity);

                return Redirect(GetRedirectUrl(model.ReturnUrl));
            }

            ModelState.AddModelError("", "Invalid email or password");
            return View();
        }

        [HttpGet]
        public ActionResult Logout()
        {
            var authManager = GetAuthManager();

            authManager.SignOut("ApplicationCookie");

            return RedirectToAction("Index", "Home", new { loggedOut = 1 });
        }

        [HttpGet]
        [AllowAnonymous]
        public ActionResult Register()
        {
            var model = new UserRegistrationViewModel()
            {
                
            };
            return View(model);
        }

        [HttpPost]
        [AllowAnonymous]
        public async Task<ActionResult> Register(UserRegistrationViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }

            var user = new User()
            {
                Email = model.Email,
                FirstName = model.FirstName,
                LastName = model.LastName,
                DateOfBirth = model.DateOfBirth,
                UserName = model.Email
            };

            var result = await _userManager.CreateAsync(user, model.Password);

            if (result.Succeeded)
            {
                var identity = await _userManager.CreateIdentityAsync(user, DefaultAuthenticationTypes.ApplicationCookie);

                return RedirectToAction("Index", "Account");
            }

            foreach(var error in result.Errors)
            {
                ModelState.AddModelError("", error);
            }

            return RedirectToAction("Login");
        }

        private string GetRedirectUrl(string returnUrl)
        {
            if (string.IsNullOrEmpty(returnUrl) || !Url.IsLocalUrl(returnUrl))
            {
                return Url.Action("Index", "Account");
            }

            return returnUrl;
        }

        private async Task SignIn(User user)
        {
            var identity = await _userManager.CreateIdentityAsync(user, DefaultAuthenticationTypes.ApplicationCookie);

            GetAuthManager().SignIn(identity);
        }

        private IAuthenticationManager GetAuthManager()
        {
            var ctx = Request.GetOwinContext();

            return ctx.Authentication;
        }
    }
}

EasyShop.Web/Controllers/BaseController.cs
using EasyShop.Common.Interfaces;
using EasyShop.Identity;
using EasyShop.Models.Domain;
using EasyShop.Web.App_Start;
using Microsoft.AspNet.Identity;
using Ninject;
using System;
using System.Web.Mvc;
using System.Web.Routing;

namespace EasyShop.Web.Controllers
{
    public abstract class BaseController : Controller
    {
        [Inject]
        public IUnitOfWork UnitOfWork { get; set; }

        public static Func<UserManager<User>> UserManagerFactory { get; private set; }

       
        protected override void Initialize(RequestContext requestContext)
        {
            ConfigureUserManagerFactory();

            base.Initialize(requestContext);
        }

        protected override void OnActionExecuting(ActionExecutingContext filterContext)
        {
            if (!filterContext.IsChildAction)
            {
                UnitOfWork.BeginTransaction();
            }              
        }

        protected override void OnResultExecuted(ResultExecutedContext filterContext)
        {
            if (!filterContext.IsChildAction)
            {
                UnitOfWork.Commit();
            }                
        }

        private void ConfigureUserManagerFactory()
        {
            UserManagerFactory = () =>
            {
                var userStore = new UserStore<User>(UnitOfWork);
                var userManager = new UserManager<User>(userStore);
                userManager.UserValidator = new UserValidator<User>(userManager)
                {
                    AllowOnlyAlphanumericUserNames = false,
                    RequireUniqueEmail = true
                };

                return userManager;
            };
        }
    }
}

EasyShop.Web/Controllers/CloudflareController.cs
using EasyShop.Cloudflare.DNS;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace EasyShop.Web.Controllers
{
    [AllowAnonymous]
    public class CloudflareController : Controller
    {
        // GET: Cloudflare
        public ActionResult Index()
        {
            var tester = new Tester();
            ViewBag.domains = tester.TesterA();
            
            return View();
        }
    }
}

EasyShop.Web/Controllers/DesignerController.cs
using EasyShop.Common.Attributes;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Threading.Tasks;

namespace EasyShop.Web.Controllers
{
    [AllowAnonymous]
    public class DesignerController : Controller
    {
        // GET: Designer
        public ActionResult Index()
        {
            return View();
        }

        [AjaxOnly]
        [HttpPost]
        public async Task<ActionResult> ChooseTheme(int id)
        {
            throw new NotImplementedException(); 
        }

        [HttpGet]
        //[AjaxOnly]
        public async Task<ActionResult> PollPreviewWindow()
        {
            return View("Preview");
        }
    }
}

EasyShop.Web/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace EasyShop.Web.Controllers
{
    [AllowAnonymous]
    public class HomeController : BaseController
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

EasyShop.Web/Controllers/HowItWorksController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace EasyShop.Web.Controllers
{
    public class HowItWorksController : Controller
    {
        // GET: HowItWorks
        public ActionResult Index()
        {
            return View();
        }
    }
}

EasyShop.Web/Views/Cloudflare/Index.cshtml
@using CloudFlare.API.Data
@model IList<CloudFlare.API.Data.ZoneObject>

@foreach(var ob in Model)
{
    <p>
        @ob.zone_name
    </p>
}

EasyShop.Web/Views/Designer/Index.cshtml
@{
    Layout = null;
}
<!DOCTYPE html>
<html ng-app="EasyShop.Designer">
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Designer</title>
    <link rel="stylesheet" href="~/Content/designer.css" type="text/css"/>
</head>
<body class="designer">

    <header>
        <h1>
            EasyShop <i>Designer</i>
        </h1>
    </header>
    <main class="container" ui-view></main>
    <script type="text/javascript" src="~/Scripts/angular.min.js"></script>
    <script type="text/javascript" src="~/Scripts/angular-ui-router.min.js"></script>
    <script type="text/javascript" src="~/Scripts/min/app.js"></script>
</body>
</html>

EasyShop.Web/Views/Designer/Preview.cshtml
@{
    Layout = null;
}

Site preview

EasyShop.Web/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

EasyShop.Web/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

EasyShop.Web/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}


<div class="side-image">
    <div class="images-wrapper"></div>
    <div class="side-image-content">
        <h4>Topic Name</h4>
        <h1>Message with a gradient image</h1>
        <p>
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Veniam assumenda nihil suscipit obcaecati sit, cum quod corporis adipisci ipsam, fugiat, quae error. Eaque commodi, dicta quidem explicabo mollitia inventore quibusdam.
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Veniam assumenda nihil suscipit obcaecati sit, cum quod corporis adipisci ipsam, fugiat, quae error. Eaque commodi, dicta quidem explicabo mollitia inventore quibusdam.
        </p>
    </div>
</div>

EasyShop.Web/Views/HowItWorks/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<ul class="bullets">
    <li class="bullet">
        <div class="bullet-icon bullet-icon-1">
            <img src="https://raw.githubusercontent.com/thoughtbot/refills/master/source/images/placeholder_square.png" alt="">
        </div>
        <div class="bullet-content">
            <h2>This Bullet Title</h2>
            <p>Lorem dolor sit amet consectetur adipisicing elit. Doloremque, minus, blanditiis, voluptatibus nulla quia ipsam sequi quos iusto aliquam iste magnam accusamus molestias quo illum impedit. Odit officia autem.</p>
        </div>
    </li>
    <li class="bullet">
        <div class="bullet-icon bullet-icon-2">
            <img src="https://raw.githubusercontent.com/thoughtbot/refills/master/source/images/placeholder_square.png" alt="">
        </div>
        <div class="bullet-content">
            <h2>Another Bullet Title</h2>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Doloremque, minus, blanditiis, voluptatibus nulla quia ipsam sequi quos iusto aliquam iste magnam accusamus molestias quo illum.</p>
        </div>
    </li>
    <li class="bullet">
        <div class="bullet-icon bullet-icon-3">
            <img src="https://raw.githubusercontent.com/thoughtbot/refills/master/source/images/placeholder_square.png" alt="">
        </div>
        <div class="bullet-content">
            <h2>Last Bullet Title</h2>
            <p>Lorem ipsum sit amet consectetur adipisicing elit. Doloremque, minus, blanditiis, voluptatibus nulla quia ipsam sequi quos iusto aliquam iste magnam accusamus molestias quo illum impedit. Odit officia autem.</p>
        </div>
    </li>
</ul>

EasyShop.Web/Views/Shared/_Footer.cshtml
<footer class="footer" role="contentinfo">
    <div class="footer-logo">
        <img src="https://raw.githubusercontent.com/thoughtbot/refills/master/source/images/placeholder_square.png" alt="Logo image">
    </div>
    <div class="footer-links">
        <ul>
            <li><h3>Content</h3></li>
            <li><a href="javascript:void(0)">About</a></li>
            <li><a href="javascript:void(0)">Contact</a></li>
            <li><a href="javascript:void(0)">Products</a></li>
        </ul>
        <ul>
            <li><h3>Follow Us</h3></li>
            <li><a href="javascript:void(0)">Facebook</a></li>
            <li><a href="javascript:void(0)">Twitter</a></li>
            <li><a href="javascript:void(0)">YouTube</a></li>
        </ul>
        <ul>
            <li><h3>Legal</h3></li>
            <li><a href="javascript:void(0)">Terms and Conditions</a></li>
            <li><a href="javascript:void(0)">Privacy Policy</a></li>
        </ul>
    </div>
    <hr>
    <p>Disclaimer area lorem ipsum dolor sit amet, consectetur adipisicing elit. Rerum, nostrum repudiandae saepe.</p>
</footer>

EasyShop.Web/Views/Shared/_Header.cshtml
<header class="centered-navigation" role="banner">
    <div class="centered-navigation-wrapper">
        <a href="javascript:void(0)" class="mobile-logo">
            <img src="https://raw.githubusercontent.com/thoughtbot/refills/master/source/images/placeholder_square.png" alt="Logo image">
        </a>
        <a href="javascript:void(0)" id="js-centered-navigation-mobile-menu" class="centered-navigation-mobile-menu">MENU</a>
        <nav role="navigation">
            <ul id="js-centered-navigation-menu" class="centered-navigation-menu show">
                <li class="nav-link"><a href="@Url.Action("Index", "HowItWorks")">How It Works</a></li>
                @if (User.Identity.IsAuthenticated)
                {
                    <li class="nav-link"><a href="@Url.Action("Index", "Designer")">Designer</a></li>
                }
                <li class="nav-link logo">
                    <a href="@Url.Action("Index", "Home")" class="logo">
                        <img src="https://raw.githubusercontent.com/thoughtbot/refills/master/source/images/placeholder_square.png" alt="Logo image">
                    </a>
                </li>
                <li class="nav-link"><a href="javascript:void(0)">Contact</a></li>
                <li id="js-centered-more" class="nav-link more">
                    <a href="javascript:void(0)">Documentation</a>
                    <ul class="submenu">
                        <li><a href="javascript:void(0)">Submenu Item</a></li>
                        <li><a href="javascript:void(0)">Another Item</a></li>
                        <li class="more">
                            <a href="javascript:void(0)">Item with submenu</a>
                            <ul class="submenu fly-out-right">
                                <li><a href="javascript:void(0)">Sub-submenu Item</a></li>
                                <li><a href="javascript:void(0)">Another Item</a></li>
                            </ul>
                        </li>
                        <li class="more">
                            <a href="javascript:void(0)">Another submenu</a>
                            <ul class="submenu fly-out-right">
                                <li><a href="javascript:void(0)">Sub-submenu</a></li>
                                <li><a href="javascript:void(0)">An Item</a></li>
                            </ul>
                        </li>
                    </ul>
                </li>
                @if (User.Identity.IsAuthenticated)
                {
                    <li class="nav-link">
                        <a href="@Url.Action("Logout", "Auth")">
                            Log out
                        </a>
                    </li>
                }
                else
                {
                    <li class="nav-link"><a href="@Url.Action("Register", "Auth")">Sign up</a> <i>or</i> <a href="@Url.Action("Login", "Auth")">Login</a></li>
                }
                
            </ul>
        </nav>
    </div>
</header>

EasyShop.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta charset="utf-8" />
    <title>@ViewBag.Title - EasyShop</title>
    <link rel="stylesheet" href="~/Content/main.css" type="text/css"/>
</head>
<body>
    @Html.Partial("_Header")

    <main>
        @RenderBody()
    </main>   
    @Html.Partial("_Footer")

    <script src="~/Scripts/min/"></script>
    @RenderSection("scripts", required: false)
</body>

</html>